### ISSUE TITLE
Set up repository structure

### ISSUE THREAD

**Issue by jbusecke** [m2lines/ocean_emulators#3]
Lets start this off right by setting up the repo for better compatibility and maintainability

- [x] Manage issues in a project --> https://github.com/orgs/m2lines/projects/8/views/1
- [x] Set up unit_testing as CI --> #4 
- [x] Set up linting with pre-commit #5 
- [x] Optional: Do we want to actually package this code at some point? I could set up a skeleton for that --> #4 
- [ ] Set up a documentation build
